// Stopwords standard italiane e inglesi.
// Fonte di riferimento: NLTK stopwords + Snowball, ristrette alle forme comuni.

export const STOPWORDS_IT = new Set([
  "a","abbia","abbiamo","abbiano","abbiate","ad","adesso","agli","ai","al","alcuna","alcuni","alcuno","all","alla","alle","allo","allora","altri","altro","anche","ancora","avendo","avere","averli","avete","aveva","avevamo","avevano","avevi","avevo","avrai","avranno","avrebbe","avrebbero","avrei","avremmo","avremo","avreste","avresti","avrete","avrà","avrò","avuta","avute","avuti","avuto","basta","bene","c","che","chi","ci","ciascuna","ciascuno","cioè","coi","col","colei","coloro","colui","come","con","contro","cosa","così","cui","da","dagli","dai","dal","dall","dalla","dalle","dallo","degli","dei","del","dell","della","delle","dello","detto","devo","di","dice","diciamo","dico","dire","dopo","dove","e","eccetera","ecco","ed","egli","eh","ehi","ehm","ella","ero","essendo","essere","essi","esso","etc","fa","fai","fanno","farai","faranno","fare","farebbe","farebbero","farei","faremo","fareste","faresti","farete","farà","farò","fatto","fece","fecero","feci","forse","fosse","fossero","fossi","fossimo","fu","fui","fummo","furono","già","gli","ha","hai","hanno","ho","i","il","in","infatti","inoltre","io","l","la","le","lei","li","lo","loro","lui","ma","mai","me","medesimo","mediante","meglio","mentre","mi","mia","mie","miei","mio","ne","negli","nei","nel","nell","nella","nelle","nello","nessuna","nessuno","no","noi","non","nostra","nostre","nostri","nostro","o","od","oppure","ora","ormai","ossia","ovvero","per","perché","però","più","poco","poi","prima","propria","proprie","propri","proprio","qua","quale","quali","qualunque","quando","quasi","quegli","quei","quel","quella","quelle","quelli","quello","questa","queste","questi","questo","qui","quindi","sarai","saranno","sarebbe","sarebbero","sarei","saremmo","saremo","sareste","saresti","sarete","sarà","sarò","se","seco","secondo","sei","sembra","senza","si","sia","siamo","siano","siate","siete","solo","sono","sopra","sotto","sta","staranno","sto","su","sua","sue","sugli","sui","sul","sull","sulla","sulle","sullo","suo","suoi","ti","tra","tre","troppo","tu","tua","tue","tuo","tuoi","tutta","tutte","tutti","tutto","un","una","uno","va","vai","vanno","verso","vi","voi","vostra","vostre","vostri","vostro","è",
]);

export const STOPWORDS_EN = new Set([
  "a","about","above","after","again","against","all","am","an","and","any","are","aren","as","at","be","because","been","before","being","below","between","both","but","by","can","couldn","did","didn","do","does","doesn","doing","don","down","during","each","few","for","from","further","had","hadn","has","hasn","have","haven","having","he","her","here","hers","herself","him","himself","his","how","i","if","in","into","is","isn","it","its","itself","just","ll","m","ma","me","might","mightn","more","most","must","mustn","my","myself","needn","no","nor","not","now","o","of","off","on","once","only","or","other","our","ours","ourselves","out","over","own","re","s","same","shan","she","should","shouldn","so","some","such","t","than","that","the","their","theirs","them","themselves","then","there","these","they","this","those","through","to","too","under","until","up","ve","very","was","wasn","we","were","weren","what","when","where","which","while","who","whom","why","will","with","won","would","wouldn","y","you","your","yours","yourself","yourselves",
]);

export function getStopwords(lang) {
  if (lang === "english") return STOPWORDS_EN;
  return STOPWORDS_IT;
}
